openapi: 3.1.0
info:
  title: Twitter API OAuth 2.0 Application
  description: A Flask-based API to authenticate users via Twitter OAuth 2.0 and post tweets with optional media.
  version: 1.0.0
servers:
  - url: https://d7ed-192-34-101-22.ngrok-free.app
    description: Local development server
paths:
  /:
    get:
      operationId: home
      summary: Welcome message
      description: Returns a welcome message for the API.
      responses:
        '200':
          description: A successful response
          content:
            text/plain:
              schema:
                type: string
                example: Welcome to the Twitter API OAuth 2.0 App!

  /startAuth:
    get:
      operationId: startAuth
      summary: Start the OAuth 2.0 flow
      description: Returns the authorization URL for the user to authenticate via Twitter.
      responses:
        '200':
          description: Authorization URL generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Authorization URL generated successfully.
                  authorization_url:
                    type: string
                    format: uri
                    example: https://twitter.com/i/oauth2/authorize?response_type=code&client_id=YOUR_CLIENT_ID...
                  state:
                    type: string
                    example: state_value
        '500':
          description: Failed to generate the authorization URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to generate authorization URL.
                  details:
                    type: string
                    example: Error message

  /callback:
    get:
      operationId: callback
      summary: Handle callback and generate access token
      description: Handles the callback from Twitter and generates an access token for the authenticated user.
      parameters:
        - name: code
          in: query
          required: true
          description: Authorization code from Twitter
          schema:
            type: string
        - name: state
          in: query
          required: true
          description: State parameter for CSRF protection
          schema:
            type: string
      responses:
        '200':
          description: Access token generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Authentication successful!
                  access_token:
                    type: string
                  expires_at:
                    type: string
                    format: date-time
                  scope:
                    type: string
                    example: tweet.write users.read tweet.read
        '400':
          description: Invalid or missing parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Authorization code not found in the callback URL.
        '500':
          description: Failed to generate access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to generate access token.
                  details:
                    type: string
                    example: Error message

  /postTweet:
    post:
      operationId: postTweet
      summary: Post a tweet
      description: Posts a tweet on behalf of the authenticated user, with optional media.
      requestBody:
        description: The content of the tweet and an optional media URL.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The content of the tweet
                  example: Hello, this is a test tweet!
                media_url:
                  type: string
                  format: uri
                  description: URL of the media to attach to the tweet
                  example: https://example.com/path/to/image.jpg
      responses:
        '201':
          description: Tweet posted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tweet posted successfully!
                  tweet_id:
                    type: string
                  tweet_text:
                    type: string
                  tweet_url:
                    type: string
                    format: uri
                    example: https://twitter.com/user/status/1234567890
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Either tweet text or media_url is required
        '401':
          description: Access token expired or missing
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Access token expired or missing. Reauthenticate.
        '500':
          description: Failed to post tweet
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to post tweet: Error message
